services:
  - mssql2012sp1

environment:
  Nkv_Tests_SqlConnectionString: Server=(local)\SQL2012SP1;Database=master;User ID=sa;Password=Password12!
  Nkv_Tests_SqlDatabase: master
  Nkv_Tests_SqlMasterConnectionString: Server=(local)\SQL2012SP1;Database=master;User ID=sa;Password=Password12!

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.1.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

branches:
  only:
    - master
    - release

configuration: Release
platform: AnyCPU

before_build:
  - nuget restore

build:
  publish_nuget: true

deploy:
  provider: NuGet
  server:
  on:
    branch: release
  api_key:
    secure: 3WN3MqedM2twg3Xe39gPfz3b3lJZt1x2aLd7k8ALaooK4oKBbiv+na5bho8Nmdbz
  artifact: /.*\.nupkg/